version: "3.9"

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/salesupport
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=super-secret
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_EXPIRE=60
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesupport
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery:
    build: ./backend
    command: celery -A app.workers.celery_app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/salesupport
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis
volumes:
  postgres_data:
